.TH ALIGN_SCORE 1 2024-Sep "" "align_score"
.SH NAME
align_score \- align_score(a, b)
.SH SYNOPSIS
\fIalign_score(a, b)\fR
.SH OPTIONS
.PP
\fBa\fB \fR\- . 
.PP
.PP
\fBb\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.align_score at molecular_tree.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
