.TH MOLECULAR_TREE 1 2024-Sep "" "Make metabolite clustering based on their structures similarity"
.SH NAME
molecular_tree \- molecular_tree(refmet,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fImolecular_tree(refmet,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBrefmet\fB \fR\- . the vector embedding result of the reference metabolites, which is parsed via the ``molecular_vector`` function.
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.molecular_tree at molecular_tree.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
