.TH MOLECULAR_TREE 1 2024-Sep "" "Make metabolite clustering via UMAP algorithm"
.SH NAME
molecular_tree \- molecular_tree(refmet)
.SH SYNOPSIS
\fImolecular_tree(refmet)\fR
.SH OPTIONS
.PP
\fBrefmet\fB \fR\- . the sgt vector embedding result of the reference metabolites, which is parsed via the ``molecular_vector`` and ``embedding_vec`` function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.molecular_tree at molecular_tree.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
