.TH MOLECULAR_TREE 1 2024-Jul "" "Make metabolite clustering based on their structures similarity"
.SH NAME
molecular_tree \- molecular_tree(refmet)
.SH SYNOPSIS
\fImolecular_tree(refmet)\fR
.SH OPTIONS
.PP
\fBrefmet\fB \fR\- . the vector embedding result of the reference metabolites, which is parsed via the ``molecular_vector`` function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.molecular_tree at molecular_tree.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
